import { User, Pet, Post, Milestone } from '../types';

// ============================================================
//  Demo 种子数据 — 面试/作品集展示用
//  首次打开自动填充，用户可在「我的 → 数据管理」中清空或恢复
// ============================================================

export const initialUsers: User[] = [
  {
    id: 'demo_user_1',
    name: '安提尔',
    avatar: '/antuer.png',
    createdAt: '2024-01-15T10:00:00.000Z',
  },
];

// ── 三只宠物 ──────────────────────────────────────────────────

export const initialPets: Pet[] = [
  {
    id: 'demo_pet_1',
    name: '旺财',
    categoryId: 'dog',
    subCategoryId: 'golden_retriever',
    gender: 'male',
    birthDate: '2022-03-12',
    birthDateType: 'exact',
    homeDate: '2022-05-20',
    avatar: '/wangcai.jpg',
    inviteCode: 'DOG123',
    ownerUserId: 'demo_user_1',
    sharedUserIds: [],
  },
  {
    id: 'demo_pet_2',
    name: '咪咪',
    categoryId: 'cat',
    subCategoryId: 'british_shorthair',
    gender: 'female',
    birthDate: '2023-06-08',
    birthDateType: 'exact',
    homeDate: '2023-08-15',
    avatar: '/mimi.jpg',
    inviteCode: 'CAT456',
    ownerUserId: 'demo_user_1',
    sharedUserIds: [],
  },
  {
    id: 'demo_pet_3',
    name: '团子',
    categoryId: 'dog',
    subCategoryId: 'corgi',
    gender: 'male',
    birthDate: '2024-01-20',
    birthDateType: 'exact',
    homeDate: '2024-03-10',
    avatar: '/tuanzi.jpg',
    inviteCode: 'COR789',
    ownerUserId: 'demo_user_1',
    sharedUserIds: [],
  },
];

// ── 旺财的健康记录（金毛 · 4 岁）─────────────────────────────

const wangcaiMilestones: Milestone[] = [
  {
    id: 'demo_ms_1_1',
    petId: 'demo_pet_1',
    type: 'home',
    title: '到家',
    description: '旺财来到新家的第一天，怯生生地躲在沙发后面',
    date: '2022-05-20',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_1_2',
    petId: 'demo_pet_1',
    type: 'anniversary',
    title: '生日',
    description: '旺财的生日',
    date: '2022-03-12',
    icon: 'anniversary',
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_1_3',
    petId: 'demo_pet_1',
    type: 'vaccine',
    title: '犬三联疫苗（第一针）',
    description: '在瑞鹏宠物医院完成犬瘟热-细小-腺病毒三联疫苗首免',
    date: '2022-06-05',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_1_4',
    petId: 'demo_pet_1',
    type: 'vaccine',
    title: '犬三联疫苗（第二针）',
    description: '三联疫苗加强针，医生说旺财状态很好',
    date: '2022-07-03',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_1_5',
    petId: 'demo_pet_1',
    type: 'vaccine',
    title: '狂犬疫苗',
    description: '满 3 月龄后接种狂犬疫苗，社区免费点打的',
    date: '2022-07-03',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_1_6',
    petId: 'demo_pet_1',
    type: 'deworm',
    title: '体内驱虫',
    description: '口服拜宠清，体重 8kg 剂量',
    date: '2022-08-10',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
    metrics: { weight_kg: 8 },
  },
  {
    id: 'demo_ms_1_7',
    petId: 'demo_pet_1',
    type: 'weight',
    title: '体重记录',
    description: '6 个月体重 18kg，医生说偏瘦要加餐',
    date: '2022-09-12',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
    metrics: { weight_kg: 18 },
  },
  {
    id: 'demo_ms_1_8',
    petId: 'demo_pet_1',
    type: 'neuter',
    title: '绝育手术',
    description: '在瑞鹏完成绝育手术，术后恢复良好，7 天拆线',
    date: '2023-01-15',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_1_9',
    petId: 'demo_pet_1',
    type: 'vaccine',
    title: '年度加强针',
    description: '犬三联 + 狂犬年度加强免疫',
    date: '2023-07-05',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_1_10',
    petId: 'demo_pet_1',
    type: 'weight',
    title: '体重记录',
    description: '2 岁体检，体重 28kg，体态评分 5/9 正常',
    date: '2024-03-12',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
    metrics: { weight_kg: 28 },
  },
  {
    id: 'demo_ms_1_11',
    petId: 'demo_pet_1',
    type: 'medical',
    title: '年度体检',
    description: '血常规、肝肾功能正常，髋关节 X 光未见异常，医生建议控制体重',
    date: '2025-03-15',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_1_12',
    petId: 'demo_pet_1',
    type: 'vaccine',
    title: '年度加强针',
    description: '犬三联 + 狂犬年度加强免疫',
    date: '2026-06-06',
    icon: 'vaccine', reminder_interval: 365,
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_1_13',
    petId: 'demo_pet_1',
    type: 'deworm',
    title: '体内外驱虫',
    description: '超可信体内外同驱，体重 29kg 剂量',
    date: '2026-06-21',
    icon: 'deworm', reminder_interval: 30,
    authorUserId: 'demo_user_1', isAI: false,
    metrics: { weight_kg: 29 },
  },
  {
    id: 'demo_ms_1_14',
    petId: 'demo_pet_1',
    type: 'bath',
    title: '洗澡美容',
    description: '夏天到了，剃短了一点毛，洗完香喷喷',
    date: '2026-06-01',
    icon: 'bath', reminder_interval: 30,
    authorUserId: 'demo_user_1', isAI: false,
  },
];

// ── 咪咪的健康记录（英短蓝猫 · 3 岁）─────────────────────────

const mimiMilestones: Milestone[] = [
  {
    id: 'demo_ms_2_1',
    petId: 'demo_pet_2',
    type: 'home',
    title: '到家',
    description: '咪咪从猫舍接回家，一路上喵喵叫，到家后钻进猫窝不出来',
    date: '2023-08-15',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_2_2',
    petId: 'demo_pet_2',
    type: 'anniversary',
    title: '生日',
    description: '咪咪的生日',
    date: '2023-06-08',
    icon: 'anniversary',
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_2_3',
    petId: 'demo_pet_2',
    type: 'vaccine',
    title: '猫三联疫苗（第一针）',
    description: '猫瘟-鼻气管炎-杯状病毒三联首免',
    date: '2023-08-28',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_2_4',
    petId: 'demo_pet_2',
    type: 'vaccine',
    title: '猫三联疫苗（第二针）',
    description: '三联加强针 + 狂犬疫苗同时接种',
    date: '2023-09-25',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_2_5',
    petId: 'demo_pet_2',
    type: 'deworm',
    title: '体内外驱虫',
    description: '大宠爱滴剂外驱 + 拜宠清内驱',
    date: '2023-10-15',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
    metrics: { weight_kg: 3.2 },
  },
  {
    id: 'demo_ms_2_6',
    petId: 'demo_pet_2',
    type: 'neuter',
    title: '绝育手术',
    description: '6 月龄绝育，术后戴伊丽莎白圈 7 天，恢复很快',
    date: '2023-12-10',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_2_7',
    petId: 'demo_pet_2',
    type: 'weight',
    title: '体重记录',
    description: '1 岁体检 4.1kg，医生说英短容易超重要注意控制',
    date: '2024-06-08',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
    metrics: { weight_kg: 4.1 },
  },
  {
    id: 'demo_ms_2_8',
    petId: 'demo_pet_2',
    type: 'vaccine',
    title: '年度加强针',
    description: '猫三联 + 狂犬年度加强',
    date: '2024-09-20',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_2_9',
    petId: 'demo_pet_2',
    type: 'medical',
    title: '年度体检',
    description: 'B 超显示腹部正常，牙齿有轻微牙结石，建议定期刷牙',
    date: '2025-06-10',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_2_10',
    petId: 'demo_pet_2',
    type: 'weight',
    title: '体重记录',
    description: '2 岁体重 4.8kg，体态偏胖，医生建议减肥到 4.2kg',
    date: '2025-06-10',
    icon: 'weight',
    authorUserId: 'demo_user_1', isAI: false,
    metrics: { weight_kg: 4.8 },
  },
  {
    id: 'demo_ms_2_11',
    petId: 'demo_pet_2',
    type: 'vaccine',
    title: '年度加强针',
    description: '猫三联 + 狂犬年度加强',
    date: '2026-06-10',
    icon: 'vaccine', reminder_interval: 365,
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_2_12',
    petId: 'demo_pet_2',
    type: 'deworm',
    title: '体内外驱虫',
    description: '大宠爱滴剂外驱 + 拜宠清内驱，体重 4.6kg',
    date: '2026-06-16',
    icon: 'deworm', reminder_interval: 30,
    authorUserId: 'demo_user_1', isAI: false,
    metrics: { weight_kg: 4.6 },
  },
];

// ── 团子的健康记录（柯基 · 2 岁）─────────────────────────────

const tuanziMilestones: Milestone[] = [
  {
    id: 'demo_ms_3_1',
    petId: 'demo_pet_3',
    type: 'home',
    title: '到家',
    description: '团子从朋友家领养，第一天就在客厅跑来跑去，精力旺盛',
    date: '2024-03-10',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_3_2',
    petId: 'demo_pet_3',
    type: 'anniversary',
    title: '生日',
    description: '团子的生日',
    date: '2024-01-20',
    icon: 'anniversary',
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_3_3',
    petId: 'demo_pet_3',
    type: 'vaccine',
    title: '犬四联疫苗（第一针）',
    description: '犬瘟-细小-腺病毒-副流感四联首免',
    date: '2024-03-25',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_3_4',
    petId: 'demo_pet_3',
    type: 'vaccine',
    title: '犬四联疫苗（第二针）',
    description: '四联加强针，小家伙打针时很乖',
    date: '2024-04-22',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_3_5',
    petId: 'demo_pet_3',
    type: 'vaccine',
    title: '狂犬疫苗',
    description: '满 3 月龄接种狂犬疫苗',
    date: '2024-04-22',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_3_6',
    petId: 'demo_pet_3',
    type: 'deworm',
    title: '体内外驱虫',
    description: '超可信体内外同驱，体重 5.5kg 剂量',
    date: '2024-05-10',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
    metrics: { weight_kg: 5.5 },
  },
  {
    id: 'demo_ms_3_7',
    petId: 'demo_pet_3',
    type: 'bath',
    title: '第一次洗澡',
    description: '在宠物店洗的，全程瑟瑟发抖但洗完很香',
    date: '2024-05-20',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_3_8',
    petId: 'demo_pet_3',
    type: 'weight',
    title: '体重记录',
    description: '6 个月体重 9kg，柯基标准范围内',
    date: '2024-07-20',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
    metrics: { weight_kg: 9 },
  },
  {
    id: 'demo_ms_3_9',
    petId: 'demo_pet_3',
    type: 'abnormal',
    title: '软便就医',
    description: '连续两天软便，检查后是换了狗粮不适应，换回原粮后恢复正常',
    date: '2024-09-05',
    icon: 'home',
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_3_10',
    petId: 'demo_pet_3',
    type: 'neuter',
    title: '绝育手术',
    description: '1 岁半绝育，手术顺利，术后第二天就开始蹦跶',
    date: '2025-08-10',
    icon: 'neuter',
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_3_11',
    petId: 'demo_pet_3',
    type: 'vaccine',
    title: '年度加强针',
    description: '犬四联 + 狂犬年度加强免疫',
    date: '2026-06-12',
    icon: 'vaccine', reminder_interval: 365,
    authorUserId: 'demo_user_1', isAI: false,
  },
  {
    id: 'demo_ms_3_12',
    petId: 'demo_pet_3',
    type: 'bath',
    title: '夏天洗澡',
    description: '天太热了，自己在家给团子洗了个澡，疯狂甩水',
    date: '2026-06-24',
    icon: 'bath', reminder_interval: 30,
    authorUserId: 'demo_user_1', isAI: false,
  },
];

// ── 合并所有里程碑 ──────────────────────────────────────────

export const initialMilestones: Milestone[] = [
  ...wangcaiMilestones,
  ...mimiMilestones,
  ...tuanziMilestones,
];

// ── 示例动态 ─────────────────────────────────────────────────

export const initialPosts: Post[] = [
  {
    id: 'demo_post_1',
    petId: 'demo_pet_1',
    authorUserId: 'demo_user_1', isAI: false,
    content: '旺财来家里的第一天！怯生生地躲在沙发后面，用零食逗了半天才肯出来 🥹',
    media: [],
    createdAt: '2024-01-01T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_2',
    petId: 'demo_pet_1',
    authorUserId: 'demo_user_1', isAI: false,
    content: '旺财今天生日！给它买了个狗狗蛋糕，一口气全吃完了 🎂',
    media: [],
    createdAt: '2022-03-12T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_3',
    petId: 'demo_pet_1',
    authorUserId: 'demo_user_1', isAI: false,
    content: '带旺财去瑞鹏打犬三联第一针，小东西打针的时候居然一点都不怕',
    media: [],
    createdAt: '2022-06-05T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_4',
    petId: 'demo_pet_1',
    authorUserId: 'demo_user_1', isAI: false,
    content: '旺财三联疫苗加强针，医生说状态很好，夸我们家旺财是模范病人',
    media: [],
    createdAt: '2022-07-03T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_5',
    petId: 'demo_pet_1',
    authorUserId: 'demo_user_1', isAI: false,
    content: '社区免费给旺财打了狂犬疫苗，不用排队太方便了',
    media: [],
    createdAt: '2022-07-03T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_6',
    petId: 'demo_pet_1',
    authorUserId: 'demo_user_1', isAI: false,
    content: '给旺财喂了拜宠清驱虫，8kg的剂量刚好，吃完胃口还是很好',
    media: [],
    createdAt: '2022-08-10T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_7',
    petId: 'demo_pet_1',
    authorUserId: 'demo_user_1', isAI: false,
    content: '称了一下旺财6个月才18kg，医生说偏瘦要加餐，从今天起罐头加倍！',
    media: [],
    createdAt: '2022-09-12T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_8',
    petId: 'demo_pet_1',
    authorUserId: 'demo_user_1', isAI: false,
    content: '旺财绝育手术顺利，在瑞鹏做的，戴了伊丽莎白圈一脸委屈，7天后拆线',
    media: [],
    createdAt: '2023-01-15T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_9',
    petId: 'demo_pet_1',
    authorUserId: 'demo_user_1', isAI: false,
    content: '又到一年疫苗时间，犬三联+狂犬年度加强，旺财已经是老司机了完全不慌',
    media: [],
    createdAt: '2023-07-05T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_10',
    petId: 'demo_pet_1',
    authorUserId: 'demo_user_1', isAI: false,
    content: '旺财2岁体检，28kg，体态评分5/9，医生说保持得不错继续控制体重就好',
    media: [],
    createdAt: '2024-03-12T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_11',
    petId: 'demo_pet_1',
    authorUserId: 'demo_user_1', isAI: false,
    content: '年度体检血常规肝肾功能全正常，髋关节X光也没问题，金毛最怕髋关节出问题，放心了',
    media: [],
    createdAt: '2025-03-15T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_12',
    petId: 'demo_pet_1',
    authorUserId: 'demo_user_1', isAI: false,
    content: '带旺财去瑞鹏打了年度加强针，犬三联+狂犬一起打的，医生说状态很好～',
    media: [],
    createdAt: '2026-06-06T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_13',
    petId: 'demo_pet_1',
    authorUserId: 'demo_user_1', isAI: false,
    content: '旺财体内外驱虫，超可信一片搞定，体重29kg，夏天到了要注意防蜱虫',
    media: [],
    createdAt: '2026-06-21T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_14',
    petId: 'demo_pet_1',
    authorUserId: 'demo_user_1', isAI: false,
    content: '天热了带旺财去洗了个澡，把毛剃短了一点，洗完整个狗都香喷喷的',
    media: [],
    createdAt: '2026-06-01T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_15',
    petId: 'demo_pet_2',
    authorUserId: 'demo_user_1', isAI: false,
    content: '从猫舍接回咪咪，一路上喵喵叫，到家后直接钻进猫窝不肯出来，看来还得慢慢适应',
    media: [],
    createdAt: '2023-08-15T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_16',
    petId: 'demo_pet_2',
    authorUserId: 'demo_user_1', isAI: false,
    content: '咪咪一岁啦！给它开了个猫罐头大餐，小家伙吃得呼噜呼噜的',
    media: [],
    createdAt: '2023-06-08T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_17',
    petId: 'demo_pet_2',
    authorUserId: 'demo_user_1', isAI: false,
    content: '带咪咪打猫三联第一针，猫瘟-鼻气管炎-杯状病毒首免，回家后睡了一整天',
    media: [],
    createdAt: '2023-08-28T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_18',
    petId: 'demo_pet_2',
    authorUserId: 'demo_user_1', isAI: false,
    content: '咪咪三联加强针+狂犬，一次两针心疼死了，不过小家伙很勇敢',
    media: [],
    createdAt: '2023-09-25T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_19',
    petId: 'demo_pet_2',
    authorUserId: 'demo_user_1', isAI: false,
    content: '给咪咪做了体内外驱虫，大宠爱滴剂+拜宠清，体重3.2kg，小猫长得真快',
    media: [],
    createdAt: '2023-10-15T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_20',
    petId: 'demo_pet_2',
    authorUserId: 'demo_user_1', isAI: false,
    content: '咪咪6个月做绝育，戴伊丽莎白圈的样子又可怜又好笑，7天拆线后生龙活虎',
    media: [],
    createdAt: '2023-12-10T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_21',
    petId: 'demo_pet_2',
    authorUserId: 'demo_user_1', isAI: false,
    content: '咪咪1岁体检4.1kg，医生说英短容易超重要注意控制食量，看来不能太宠了',
    media: [],
    createdAt: '2024-06-08T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_22',
    petId: 'demo_pet_2',
    authorUserId: 'demo_user_1', isAI: false,
    content: '年度猫三联+狂犬加强，咪咪现在已经很淡定了，打完针就去吃罐头',
    media: [],
    createdAt: '2024-09-20T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_23',
    petId: 'demo_pet_2',
    authorUserId: 'demo_user_1', isAI: false,
    content: 'B超牙齿都检查了，腹部正常，有点牙结石，医生建议定期给咪咪刷牙…这怎么刷啊',
    media: [],
    createdAt: '2025-06-10T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_24',
    petId: 'demo_pet_2',
    authorUserId: 'demo_user_1', isAI: false,
    content: '咪咪2岁4.8kg！体态偏胖，医生严肃地说要减肥到4.2kg，以后罐头减半',
    media: [],
    createdAt: '2025-06-10T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_25',
    petId: 'demo_pet_2',
    authorUserId: 'demo_user_1', isAI: false,
    content: '带咪咪打了年度加强针，猫三联+狂犬，小家伙打针的时候一声没吭，太乖了',
    media: [],
    createdAt: '2026-06-10T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_26',
    petId: 'demo_pet_2',
    authorUserId: 'demo_user_1', isAI: false,
    content: '咪咪做体内外驱虫，大宠爱滴剂+拜宠清，体重4.6kg，最近控制饮食好像瘦了一点点',
    media: ['/mimi_0616.jpg'],
    createdAt: '2026-06-16T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_27',
    petId: 'demo_pet_3',
    authorUserId: 'demo_user_1', isAI: false,
    content: '从朋友家领养了团子，第一天就在客厅疯狂跑圈，柯基的精力果然不是盖的',
    media: [],
    createdAt: '2024-03-10T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_28',
    petId: 'demo_pet_3',
    authorUserId: 'demo_user_1', isAI: false,
    content: '团子满3个月啦！买了个小玩具给它，咬了两口就开始拆家了',
    media: [],
    createdAt: '2024-01-20T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_29',
    petId: 'demo_pet_3',
    authorUserId: 'demo_user_1', isAI: false,
    content: '团子打犬四联第一针，犬瘟-细小-腺病毒-副流感全部覆盖，打完还冲医生摇尾巴',
    media: [],
    createdAt: '2024-03-25T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_30',
    petId: 'demo_pet_3',
    authorUserId: 'demo_user_1', isAI: false,
    content: '四联加强针，团子打针的时候居然在吃零食，心也太大了',
    media: [],
    createdAt: '2024-04-22T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_31',
    petId: 'demo_pet_3',
    authorUserId: 'demo_user_1', isAI: false,
    content: '狂犬疫苗搞定，团子满3月龄就可以打了，这下疫苗本全部到位',
    media: [],
    createdAt: '2024-04-22T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_32',
    petId: 'demo_pet_3',
    authorUserId: 'demo_user_1', isAI: false,
    content: '给团子做了体内外驱虫，超可信一片，体重5.5kg，小短腿体重不轻啊',
    media: [],
    createdAt: '2024-05-10T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_33',
    petId: 'demo_pet_3',
    authorUserId: 'demo_user_1', isAI: false,
    content: '第一次带团子去宠物店洗澡，全程瑟瑟发抖但洗完超香的，柯基的小短腿站在浴缸里太萌了',
    media: [],
    createdAt: '2024-05-20T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_34',
    petId: 'demo_pet_3',
    authorUserId: 'demo_user_1', isAI: false,
    content: '团子6个月9kg了，医生说柯基标准范围内不算胖，放心了',
    media: [],
    createdAt: '2024-07-20T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_35',
    petId: 'demo_pet_3',
    authorUserId: 'demo_user_1', isAI: false,
    content: '团子连续两天软便，吓坏了赶紧去医院，结果是换的狗粮不适应，换回原来的就好了',
    media: [],
    createdAt: '2024-09-05T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_36',
    petId: 'demo_pet_3',
    authorUserId: 'demo_user_1', isAI: false,
    content: '团子绝育手术顺利，术后第二天就开始蹦跶…医生说静养它根本不当回事',
    media: [],
    createdAt: '2025-08-10T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_37',
    petId: 'demo_pet_3',
    authorUserId: 'demo_user_1', isAI: false,
    content: '带团子去打年度加强针，犬四联+狂犬，这小子在候诊室跟一只法斗吵起来了',
    media: [],
    createdAt: '2026-06-12T10:00:00.000Z',
    comments: [],
    likes: [],
  },
  {
    id: 'demo_post_38',
    petId: 'demo_pet_3',
    authorUserId: 'demo_user_1', isAI: false,
    content: '天太热了在家给团子洗澡，疯狂甩水甩了我一身，洗完整只狗都在地上蹭',
    media: [],
    createdAt: '2026-06-24T10:00:00.000Z',
    comments: [],
    likes: [],
  }
];
